import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  FaCertificate, FaLeaf, FaSeedling, FaAward,
  FaDownload, FaShare, FaPrint, FaTimes,
  FaCheckCircle, FaUser, FaCalendar, FaTag
} from 'react-icons/fa';
import toast from 'react-hot-toast';

const CertificateGenerator = ({ onClose }) => {
  const [formData, setFormData] = useState({
    farmerName: '',
    farmName: '',
    productName: '',
    certificateType: 'organic',
    issueDate: new Date().toISOString().split('T')[0],
    expiryDate: '',
    batchNumber: '',
    certificationBody: 'AgroValue Connect',
    additionalInfo: ''
  });

  const [generated, setGenerated] = useState(false);
  const [certificateId, setCertificateId] = useState('');

  const certificateTypes = [
    { value: 'organic', label: 'Organic Certification', icon: FaLeaf, color: 'green' },
    { value: 'quality', label: 'Quality Assurance', icon: FaCheckCircle, color: 'blue' },
    { value: 'fair-trade', label: 'Fair Trade', icon: FaAward, color: 'purple' },
    { value: 'sustainable', label: 'Sustainable Farming', icon: FaSeedling, color: 'emerald' }
  ];

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const generateCertificate = () => {
    if (!formData.farmerName || !formData.productName) {
      toast.error('Please fill in farmer name and product name');
      return;
    }

    // Generate unique certificate ID
    const id = `CERT-${new Date().getFullYear()}-${Math.random().toString(36).substr(2, 8).toUpperCase()}`;
    setCertificateId(id);
    setGenerated(true);
    
    toast.success('Certificate generated successfully!');
  };

  const downloadCertificate = () => {
    // Create certificate content
    const certificateContent = `
      CERTIFICATE OF ${formData.certificateType.toUpperCase()}
      
      Certificate ID: ${certificateId}
      Issue Date: ${formData.issueDate}
      ${formData.expiryDate ? `Expiry Date: ${formData.expiryDate}` : ''}
      
      This is to certify that
      
      ${formData.farmerName}
      ${formData.farmName ? `of ${formData.farmName}` : ''}
      
      has demonstrated compliance with the ${certificateTypes.find(t => t.value === formData.certificateType)?.label} standards
      for the following product:
      
      ${formData.productName}
      ${formData.batchNumber ? `Batch: ${formData.batchNumber}` : ''}
      
      Certified by: ${formData.certificationBody}
      
      ${formData.additionalInfo ? `Additional Information: ${formData.additionalInfo}` : ''}
      
      ---
      This certificate is generated by AgroValue Connect
      Verification: https://agrovalueconnect.com/verify/${certificateId}
    `;

    const blob = new Blob([certificateContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `certificate-${certificateId}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);
    
    toast.success('Certificate downloaded!');
  };

  const shareCertificate = () => {
    const text = `I just got my ${certificateTypes.find(t => t.value === formData.certificateType)?.label} for ${formData.productName} on AgroValue Connect!`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const printCertificate = () => {
    window.print();
  };

  const selectedType = certificateTypes.find(t => t.value === formData.certificateType);

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 overflow-y-auto">
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="bg-white rounded-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto"
      >
        {/* Header */}
        <div className={`bg-gradient-to-r from-${selectedType?.color}-600 to-${selectedType?.color}-700 p-6 text-white sticky top-0`}>
          <div className="flex justify-between items-start">
            <div className="flex items-center space-x-3">
              <FaCertificate className="text-3xl" />
              <div>
                <h2 className="text-2xl font-bold">Certificate Generator</h2>
                <p className={`text-${selectedType?.color}-100`}>Create quality certificates for your products</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 hover:bg-white/20 rounded-lg transition"
            >
              <FaTimes />
            </button>
          </div>
        </div>

        <div className="p-6">
          <div className="grid md:grid-cols-2 gap-6">
            {/* Certificate Form */}
            <div className="space-y-4">
              <h3 className="font-semibold text-lg">Certificate Details</h3>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Certificate Type
                </label>
                <div className="grid grid-cols-2 gap-2">
                  {certificateTypes.map(type => {
                    const Icon = type.icon;
                    return (
                      <button
                        key={type.value}
                        onClick={() => setFormData(prev => ({ ...prev, certificateType: type.value }))}
                        className={`p-3 border-2 rounded-xl flex flex-col items-center space-y-2 transition ${
                          formData.certificateType === type.value
                            ? `border-${type.color}-500 bg-${type.color}-50`
                            : 'border-gray-200 hover:border-gray-300'
                        }`}
                      >
                        <Icon className={`text-xl ${formData.certificateType === type.value ? `text-${type.color}-600` : 'text-gray-400'}`} />
                        <span className="text-xs text-center">{type.label}</span>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Farmer Name *
                </label>
                <input
                  type="text"
                  name="farmerName"
                  value={formData.farmerName}
                  onChange={handleChange}
                  placeholder="Enter farmer's full name"
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Farm Name (Optional)
                </label>
                <input
                  type="text"
                  name="farmName"
                  value={formData.farmName}
                  onChange={handleChange}
                  placeholder="Enter farm name"
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Product Name *
                </label>
                <input
                  type="text"
                  name="productName"
                  value={formData.productName}
                  onChange={handleChange}
                  placeholder="e.g., Organic Honey"
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Batch Number (Optional)
                </label>
                <input
                  type="text"
                  name="batchNumber"
                  value={formData.batchNumber}
                  onChange={handleChange}
                  placeholder="e.g., BATCH-2024-001"
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>
            </div>

            {/* Dates & Additional Info */}
            <div className="space-y-4">
              <h3 className="font-semibold text-lg">Validity & Additional Info</h3>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Issue Date
                </label>
                <input
                  type="date"
                  name="issueDate"
                  value={formData.issueDate}
                  onChange={handleChange}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Expiry Date (Optional)
                </label>
                <input
                  type="date"
                  name="expiryDate"
                  value={formData.expiryDate}
                  onChange={handleChange}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Certification Body
                </label>
                <input
                  type="text"
                  name="certificationBody"
                  value={formData.certificationBody}
                  onChange={handleChange}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Additional Information (Optional)
                </label>
                <textarea
                  name="additionalInfo"
                  value={formData.additionalInfo}
                  onChange={handleChange}
                  rows="3"
                  placeholder="Any additional notes or information..."
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>
            </div>
          </div>

          {/* Generate Button */}
          <div className="flex justify-end mt-6 pt-6 border-t">
            <button
              onClick={generateCertificate}
              className={`px-8 py-3 bg-gradient-to-r from-${selectedType?.color}-600 to-${selectedType?.color}-700 text-white rounded-lg hover:shadow-lg transition font-semibold`}
            >
              Generate Certificate
            </button>
          </div>

          {/* Generated Certificate Preview */}
          {generated && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className={`mt-6 bg-gradient-to-br from-${selectedType?.color}-50 to-white rounded-xl p-8 border-2 border-${selectedType?.color}-200`}
            >
              <div className="text-center mb-6">
                <FaCertificate className={`text-5xl mx-auto mb-2 text-${selectedType?.color}-600`} />
                <h3 className={`text-2xl font-bold text-${selectedType?.color}-800`}>
                  {certificateTypes.find(t => t.value === formData.certificateType)?.label}
                </h3>
                <p className="text-gray-600 mt-1">Certificate of Authentication</p>
              </div>

              <div className="border-t-2 border-dashed border-gray-300 pt-6">
                <div className="grid grid-cols-2 gap-4 mb-6">
                  <div>
                    <p className="text-sm text-gray-500">Certificate ID</p>
                    <p className="font-mono font-semibold">{certificateId}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">Issue Date</p>
                    <p>{new Date(formData.issueDate).toLocaleDateString()}</p>
                  </div>
                </div>

                <div className="text-center mb-6">
                  <p className="text-sm text-gray-500 mb-1">This is to certify that</p>
                  <p className="text-2xl font-bold text-gray-800">{formData.farmerName}</p>
                  {formData.farmName && (
                    <p className="text-lg text-gray-600">{formData.farmName}</p>
                  )}
                </div>

                <div className="text-center mb-6">
                  <p className="text-sm text-gray-500 mb-1">has demonstrated excellence in producing</p>
                  <p className="text-xl font-bold text-primary-600">{formData.productName}</p>
                  {formData.batchNumber && (
                    <p className="text-sm text-gray-600">Batch: {formData.batchNumber}</p>
                  )}
                </div>

                <div className="flex justify-center space-x-4 text-sm text-gray-500 mb-6">
                  <span>Certified by: {formData.certificationBody}</span>
                </div>

                {formData.additionalInfo && (
                  <div className="bg-gray-50 p-3 rounded-lg mb-6">
                    <p className="text-sm text-gray-600">{formData.additionalInfo}</p>
                  </div>
                )}

                {/* Action Buttons */}
                <div className="flex justify-center space-x-4">
                  <button
                    onClick={downloadCertificate}
                    className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
                  >
                    <FaDownload />
                    <span>Download</span>
                  </button>
                  <button
                    onClick={shareCertificate}
                    className="flex items-center space-x-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition"
                  >
                    <FaShare />
                    <span>Share</span>
                  </button>
                  <button
                    onClick={printCertificate}
                    className="flex items-center space-x-2 px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition"
                  >
                    <FaPrint />
                    <span>Print</span>
                  </button>
                </div>

                <p className="text-xs text-center text-gray-400 mt-4">
                  Verify this certificate at: https://agrovalueconnect.com/verify/{certificateId}
                </p>
              </div>
            </motion.div>
          )}
        </div>
      </motion.div>
    </div>
  );
};

export default CertificateGenerator;